- geocoding/CHANGELOG.md
- geocoding/android/src/main/java/com/baseflow/geocoding/MethodCallHandlerImpl.java
- geocoding/ios/Classes/GeocodingPlugin.m
- geocoding/ios/geocoding.podspec
- geocoding/lib/geocoding.dart
- geocoding/pubspec.yaml
Bug fix
Currently the `localeIdentifier` is not past correctly to the native side of the plugin.
Correctly pass the `localeIdentifier` parameter and act accordingly.
No
1. Open the example app;
2. Pass a correctly locale identifier to the `placemarkFromCoordinates` and `locationFromAddress` methods;
3. Run the example app and verify the app displays the information in the correct locale.
Fixes #10
> Make sure the localeIdentifier is passed correctly

- README.md
- geocoding/CHANGELOG.md
- geocoding/example/ios/Runner.xcodeproj/project.pbxproj
- geocoding/ios/Classes/GeocodingHandler.m
- geocoding/pubspec.yaml
- geocoding_platform_interface/CHANGELOG.md
- geocoding_platform_interface/lib/geocoding_platform_interface.dart
- geocoding_platform_interface/lib/src/errors/errors.dart
- geocoding_platform_interface/lib/src/errors/no_result_found_exception.dart
- geocoding_platform_interface/lib/src/implementations/method_channel_geocoding.dart
- geocoding_platform_interface/pubspec.yaml
- geocoding_platform_interface/test/src/implementations/method_channel_geocoding_test.dart
Added NoResultsException, to improve the understandability of the exceptions thrown.  
Throws PlatformException when on results are found
Throws NoResultsFoundException when no results found
No, but error handling should be done differently.  
Enter gibberish in the address field in the example plugin
> NoResultFoundException

- README.md
A documentation fix.
The method name in the documentation (README) refers to an outdated name.
It refers to the correct name.
No :+1:
> Fix documentation referring to old method name

- .github/no-response.yml
Make sure the no-response GitHub App filters on the correct "status: needs more info" label.
> Filter on correct label

- geocoding/CHANGELOG.md
- geocoding/README.md
- geocoding/android/build.gradle
- geocoding/example/android/app/build.gradle
- geocoding/pubspec.yaml
This PR fixes https://github.com/Baseflow/flutter-geocoding/issues/87 which prevents, Flutter apps compiling to Android SDK 31, to build.
Build fails for Flutter applications compiling for Android SDK 31
Build works fine for flutter applications compiling for Android SDK 31
Yes, current clients must also upgrade to `compileSdkVersion 31` on `android/app/build.gradle`, when using this version of `flutter-geocoding`
Run example app or any other application on Android device/emulator with `compileSdkVersion 31` on `android/app/build.gradle`
None
> Upgrade compileSdkVersion to 31

- .github/workflows/app_facing_package.yaml
- geocoding/CHANGELOG.md
- geocoding/android/src/main/java/com/baseflow/geocoding/GeocodingPlugin.java
- geocoding/example/android/app/build.gradle
- geocoding/example/android/app/src/main/AndroidManifest.xml
- geocoding/test/geocoding_test.dart
Big fix
Compiling the Android example app results in an Android embedding deprecation warning.
Resolved the deprecated issue. Building the Android example App no longer results in the deprecation warning.
No
```shell
cd example
flutter build appbundle
```
> Fix Android embedding deprecation warning

- geocoding/CHANGELOG.md
- geocoding/README.md
- geocoding/pubspec.yaml
Documentation update
The link to the Android migration guide is not working properly on pub.dev.
Restructure the link so it also works correctly on pub.dev.
No
Solves #73
> Fixes link to Android migration guide

- geocoding_platform_interface/test/geocoding_platform_interface_test.dart
Currently, in some circumstances where a subclasses of
`PlatformInterface` erroneously uses `implements` rather than
`extends`, a `NoSuchMethodError` will be thrown (in spite of the
documentation at
https://pub.dev/documentation/plugin_platform_interface/latest/plugin_platform_interface/PlatformInterface/verify.html
claiming that `AssertionError` will be thrown).
After https://github.com/flutter/flutter/issues/109339 is fixed, the
correct type of exception will be thrown.  To avoid a test breakage in
`geocoding_platform_interface_test.dart` when the fix happens, we need
to modify the test so that it doesn't care what kind of exception is
thrown.
Bug fix
The test expects `NoSuchMethodError` to be thrown; this will break after https://github.com/flutter/flutter/issues/109339 is fixed.
The …
> Prepare for fix to https://github.com/flutter/flutter/issues/109339.

- geocoding/CHANGELOG.md
- geocoding/pubspec.yaml
With this PR, the right section on pub.dev will show the View/report issues link to GitHub again, like [here](https://pub.dev/packages/android_id) (the show-logic was recently changed).
It shows a `Homepage` link
It shows links to `Repository (GitHub)` and `View/report issues`
No.
> Update links for pub.dev

- .github/workflows/no-response.yaml
Replaces the `no-response` bot with a more advanced version. The main reason for this change is to make sure the bot also removes the `status: needs more info` label when other contributors post an update. 
The old bot only removed the label if the original poster responded, this might lead in issues being closed while sufficient information was provided.
[Contributor Guide]: https://github.com/Baseflow/flutter-geolocator/blob/master/CONTRIBUTING.md
> Replace the stale both with more advanced version

- geocoding_ios/CHANGELOG.md
- geocoding_ios/ios/Classes/Extensions/CLPlacemarkExtensions.m
- geocoding_ios/pubspec.yaml
Resolves [142](https://github.com/Baseflow/flutter-geocoding/issues/142). Removed iOS deprecation warnings. Deleted code would never be used because the current minimal deployment target is 11.0. 
> Removes deprecation warnings. iOS 11 is minimal deployment target

- geocoding_platform_interface/CHANGELOG.md
- geocoding_platform_interface/lib/src/geocoding_platform_interface.dart
- geocoding_platform_interface/pubspec.yaml
Adds support for `placemarkFromAddress` in the geocoding platform interface.
> Add support for `placemarkFromAddress` in platform interface

- geocoding_platform_interface/pubspec.yaml
Follow-up to #178.
`flutter pub publish` revealed a warning indicating that the Dart SDK constraint should be updated.
> Update Dart SDK constraint

- geocoding_platform_interface/CHANGELOG.md
- geocoding_platform_interface/lib/src/geocoding_platform_interface.dart
- geocoding_platform_interface/pubspec.yaml
- geocoding_platform_interface/test/geocoding_platform_interface_test.dart
Implements isPresent (https://github.com/Baseflow/flutter-geocoding/issues/194)
> Expose isPresent platform interface

- geocoding_ios/CHANGELOG.md
- geocoding_ios/example/lib/plugin_example/geocode_page.dart
- geocoding_ios/ios/Classes/GeocodingPlugin.m
- geocoding_ios/lib/geocoding_ios.dart
- geocoding_ios/pubspec.yaml
Implements isPresent iOS (https://github.com/Baseflow/flutter-geocoding/issues/194)
> expose isPresent ios implementation

- geocoding/example/lib/main.dart
- geocoding/lib/geocoding.dart
- geocoding/pubspec.yaml
- geocoding/test/geocoding_test.dart
Implements: (https://github.com/Baseflow/flutter-geocoding/issues/194) and updates main package with new platform interface 3.x.x and added isPresent to the example project.
> Updated app facing package and implemented isPresent() in example project

- geocoding_ios/CHANGELOG.md
- geocoding_ios/ios/Resources/PrivacyInfo.xcprivacy
- geocoding_ios/ios/geocoding_ios.podspec
- geocoding_ios/pubspec.yaml
Adds the required privacy manifest to the iOS implementation.
Because the geocoding_ios package doesn't collect any privacy data, the privacy manifest can be empty. 
Note that we are following the standard Flutter / Cocoapods implementation which has the following caveat:
> The large caveat is that we do not currently know if this actually works. This is the method of inclusion that seems to be [the consensus among people using Cocoapods](https://github.com/CocoaPods/CocoaPods/issues/10325), as bundling it directly as a `resource` causes problems for clients who do not use `use_frameworks`. (In theory it seems like a manifest would not actually be *required* in that case since there is no framework, but it has the potential to actually stomp top-level resources.) Hopefully the automated …
> Adds iOS privacy manifest.

- geocoding_android/CHANGELOG.md
- geocoding_android/android/src/main/java/com/baseflow/geocoding/GeocodingPlugin.java
- geocoding_android/pubspec.yaml
The Flutter team is removing references to the Android V1 embedding from their code base (see flutter/flutter#144726). This would mean that code still containing references to the Android V1 embedding will no longer compile. 
This PR removes references to Android V1 embedding from the permission_handler_android plugin.
- flutter/flutter#144726
> Removes references to Android v1 embedding.

- geocoding/CHANGELOG.md
- geocoding/README.md
- geocoding/pubspec.yaml
Updated link in README.md file to use `https` (secure) instead of `http` (insecure) protocol.
Fixes the pub.dev score
> docs: use secure https link in README.md

- geocoding/example/lib/main.dart
- geocoding_android/example/lib/main.dart
- geocoding_android/example/lib/plugin_example/geocode_page.dart
- geocoding_android/example/lib/template/globals.dart
- geocoding_android/example/lib/template/info_page.dart
- geocoding_ios/example/lib/main.dart
- geocoding_ios/example/lib/plugin_example/geocode_page.dart
- geocoding_ios/example/lib/template/globals.dart
- geocoding_ios/example/lib/template/info_page.dart
Formatted code with `dart format .` and fixed linting issues with `dart fix --apply`
Fixes following reason of failed workflow: https://github.com/Baseflow/flutter-geocoding/actions/runs/11226397157/job/31206847039
> style: formatted and fixed code to resolve linting issues

- README.md
- geocoding/README.md
- geocoding_android/README.md
- geocoding_platform_interface/README.md
- Fixed `Build Status` badge not rendering properly in `root`, `geocoding` & `geocoding_platform_interface` `README.md`'s
- Updated formating for readme removing unnecessary spaces and indenting code samples for bullet points
Trivial Changes not requiring issue
> docs: fixes all formatting and link issues

- geocoding/CHANGELOG.md
- geocoding/example/android/.settings/org.eclipse.buildship.core.prefs
- geocoding/example/android/app/build.gradle
- geocoding/example/android/build.gradle
- geocoding/example/android/gradle/wrapper/gradle-wrapper.properties
- geocoding/example/android/settings.gradle
- geocoding/example/ios/Flutter/AppFrameworkInfo.plist
- geocoding/example/ios/Podfile
- geocoding/example/ios/Runner.xcodeproj/project.pbxproj
- geocoding/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- geocoding/pubspec.yaml
Updates the AFP example project
> updates geocoding AFP

- geocoding_ios/CHANGELOG.md
- geocoding_ios/example/ios/Runner.xcodeproj/project.pbxproj
- geocoding_ios/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- geocoding_ios/example/lib/main.dart
- geocoding_ios/example/lib/plugin_example/geocode_page.dart
- geocoding_ios/example/lib/template/info_page.dart
- geocoding_ios/pubspec.yaml
Updated the iOS example project to fix the deprecation warnings.
> Fixed iOS deprecation warnings
